title: Kailin Pan
# tagline: Here is personal website of Hanlin Cai. Powered by Jekyll, based on the Minimal Mistakes theme.
#Comment out url when working locally to resolve base urls correctly
url: https://kailinpan.github.io

# Owner/author information
owner:
  name: Kailin Pan
  avatar: avatar.jpg
 # bio: 
  email: kailpan@iu.edu
 # cv: https://zhenpeng-li.github.io/file/CV.pdf
 # bilibili: 667981017
  github: kailinpan
 
  #twitter: .
  #linkedin: .
  scholar: https://scholar.google.com/citations?hl=en&user=u3n0zbwAAAAJ
  #researchgate: https://www.researchgate.net
  #zhihu: https://www.zhihu.com
  #instagram: .
  arXiv: https://arxiv.org/search/math?query=Kailin+Pan&searchtype=author&abstracts=show&order=-announced_date_first&size=50
  
  #lastfm:
  #tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "t8nQeaAGZANUEqKCGZn-3GBmV46zGVLcnhpvkfdBAqE"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Research
    url: /research/
  #- title: Awards
  #  url: /awards/
  #- title: Seminars
  # url: /seminars/
  #- title: Links
  #  url: /links/
  #- title: Photos
  #  url: /photos/
  #- title: Reminiscence
  # url: /reminiscence/
    
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Indianapolis
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# Latest update in 2023/12/10 by Hanlin Cai.
